### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by TracerDS** [Ren232/mcgg#1]
Hi! I have got the server started. I have machine IP and Server IP, but I can't connect to the server. I'm using Server IP and Machine IP but it shows: 'Can't connect to the server.' Eula is true, ngrok key is given and max RAM is 1024 MB.

**Comment by Ren232** [comment]
Hello! In order to connect to your server you need to use the Ngrok IP.
If the Ngrok ip doesn't show, Goto file manager > ngrok.yml and check if your token is in there.
