### ISSUE TITLE
Login Incorrect for the 2st Login

### ISSUE THREAD

**Issue by Farhan1907s** [Ren232/mcgg#15]
Hello it's Incorrect login information for the 2st Time but the Username and password ia Correct thank you.

**Comment by Ren232** [comment]
I think you will need to setup a account at https://app_name.herokuapp.com/panel/install.php . If that doesn't work try deleting the app and redoing the installation process.

**Comment by Farhan1907** [comment]
> I think you will need to setup a account at https://app_name.herokuapp.com/panel/install.php . If that doesn't work try deleting the app and redoing the installation process.

I'm sorry for late answered. It's still. Is it because I made it more than 1024MB? But what I am very uneasy about is that the IP is always changed ... for example tcp.ngrok.io:1111 before and 1 day later it changed to: 38387 for example ..

**Comment by Farhan1907** [comment]
Tolong buat ini jadi lebih baik!
Terimakasih :")

**Comment by Ren232** [comment]
I can't fix the ip changing because that's how ngrok works.

**Comment by Farhan1907** [comment]
It is okey, but There are 0 servers running after 1 day.. 
Do you have discord or other to chat with you easy

**Comment by Ren232** [comment]
Did you signup your herokuapp at https://wakemydyno.com?
