### ISSUE TITLE
New version upload

### ISSUE THREAD

**Issue by emarsonque14** [Ren232/mcgg#2]
Hi! How can I upload a newer version e.g. 1.14.4?

**Comment by jason123santa** [comment]
I want to know how to do that to because I tired to delete the .jar and put a newer .jar but that did not work and i had to restart the dino.

**Comment by IncinerateZ** [comment]
Uploads stop halfway when uploading 'big' files (Tried on 40MB files), thus, unable to upload a custom jar file.

**Comment by jason123santa** [comment]
> Uploads stop halfway when uploading 'big' files (Tried on 40MB files), thus, unable to upload a custom jar file.

Is there a way to fix it?

**Comment by IncinerateZ** [comment]
@jason123santa I forked my own version and I managed to get 1.12 working. However for some reason the server crashes mid startup with 1.13 and 1.14 jars.

**Comment by jason123santa** [comment]
Should I use your version then? If you can't get 1.14 working then there could be a fix bu i don't know.

**Comment by IncinerateZ** [comment]
I guess you can if you want to have it running on 1.12.2. I suspect its due to low RAM since there is no other difference.

**Comment by jason123santa** [comment]
Does the deploy to heroku button work for your forked version?

**Comment by IncinerateZ** [comment]
it should.

**Comment by jason123santa** [comment]
I will try it then and tell you if it works.

**Comment by jason123santa** [comment]
@IncinerateZ I got 1.14.2 server to work on your forked version. There is some delay in doing things but it is not a huge problem since it is playable. I don't know what will happen for more then one player but i can test that. I can also test using a lower server version like 1.13 and see if that works.

**Comment by IncinerateZ** [comment]
Nice, I have no idea why it doesn't work for me, though. For me, if I try to start a 1.13 or 1.14 server, the entire server just 'vanishes' while starting up, and throws some error at me.

**Comment by jason123santa** [comment]
What error does it show when you start up the server?

**Comment by IncinerateZ** [comment]
A few seconds after starting up the server, everything stops and when I reload, it says something along the lines of "project does not exist"

**Comment by waaberi** [comment]
This should be closed cause 1.14.4 is already here
