### ISSUE TITLE
Server update to 1.16

### ISSUE THREAD

**Issue by ahmadbkevin** [Ren232/mcgg#20]
I cannot upload the jar file to update the server... pls help

**Comment by Ren232** [comment]
It's possible to change it to 1.16 by yourself by forking it and manually changing the code, although I highly doubt 1.16 would work with the limited resources of the herokuapp.

**Comment by ahmadbkevin** [comment]
Yeah true, the only thing herokuapp is good at is discord bot hosting

**Comment by ahmadbkevin** [comment]
even then its not perfect
