### ISSUE TITLE
heruko issue

### ISSUE THREAD

**Issue by AKASH-UWU** [Ren232/mcgg#25]
-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
 !     WARNING: Requested version for package 'php' not available
 !     ERROR: Failed to install system packages!
 !     
 !     Your platform requirements (for runtimes and extensions) could
 !     not be resolved to an installable set of dependencies, or a
 !     platform package repository was unreachable.
 !     
 !     This usually means that you (or packages you are using) depend
 !     on a combination of PHP versions and/or extensions that are
 !     currently not available on Heroku.
 !     
 !     The following is the full output from the installation attempt:
 !     
 !     > Loading repositories with available runtimes and extensions
 !     > Updating dependencies
 !     > Your requirements could not be resolved to an installable set of packages.
 !     > 
 !     >   Problem 1
 !     >     - composer.json/composer.lock requires php ~7.2.0 -> no matching package found.
 !     > 
 !     
 !     For reference, the following runtimes are currently available:
 !     
 !     PHP:  8.0.1, 8.0.0, 8.0.0RC4, 7.4.14, 7.4.13, 7.4.12, 7.3.26, 
 !     7.3.25, 7.3.24
 !     
 !     Please verify that all requirements for runtime versions in
 !     'composer.lock' are compatible with the list above, and ensure
 !     all required extensions are available for the desired runtimes.
 !     
 !     When choosing a PHP runtimes and extensions, please also ensure
 !     they are available on your app's stack (heroku-20), and select
 !     a different stack if needed after consulting the article below.
 !     
 !     For a list of supported runtimes & extensions on Heroku, please
 !     refer to: https://devcenter.heroku.com/articles/php-support
 !     
 !     REMINDER: the following warnings were emitted during the build;
 !     check the details above, as they may be related to this error:
 !     - Requested version for package 'php' not available
 !     Push rejected, failed to compile PHP app.
 !     Push failed

**Comment by LAW-1337** [comment]
Yeah, same problem here, I think some files are not up to date

**Comment by Ren232** [comment]
I've pushed a fix for that and it should now hopefully work.
