### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by shessafridi** [Ren232/mcgg#27]
Heroku gives me an error when I try to deploy the app, here are the logs

`-----> Building on the Heroku-20 stack
-----> JVM Common app detected
-----> Installing JDK 1.8... done
-----> Minecraft app detected
-----> Updating... 
       Get:1 http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease [81.6 kB]
       Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
       Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [109 kB]
       Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
       Get:5 http://apt.postgresql.org/pub/repos/apt focal-pgdg/main amd64 Packages [307 kB]
       Get:6 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
       Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,275 kB]
       Get:8 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [670 kB]
       Get:9 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [621 kB]
       Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,029 kB]
       Get:11 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [932 kB]
       Fetched 16.7 MB in 2s (7,019 kB/s)
       Reading package lists...
-----> Installing screen... 
       Reading package lists...
       Building dependency tree...
       The following additional packages will be installed:
         libutempter0
       Suggested packages:
         byobu | screenie | iselect ncurses-term
       The following NEW packages will be installed:
         libutempter0 screen
       0 upgraded, 2 newly installed, 0 to remove and 38 not upgraded.
       Need to get 585 kB of archives.
       After this operation, 1,073 kB of additional disk space will be used.
       Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libutempter0 amd64 1.1.6-4 [8,256 B]
       Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 screen amd64 4.8.0-1 [577 kB]
       Fetched 585 kB in 1s (991 kB/s)
       Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
-----> PHP app detected
-----> Bootstrapping...
-----> Installing platform packages...
 !     WARNING: Requested version for package 'php' not available
 !     ERROR: Failed to install system packages!
 !     
 !     Your platform requirements (for runtimes and extensions) could
 !     not be resolved to an installable set of dependencies, or a
 !     platform package repository was unreachable.
 !     
 !     This usually means that you (or packages you are using) depend
 !     on a combination of PHP versions and/or extensions that are
 !     currently not available on Heroku.
 !     
 !     The following is the full output from the installation attempt:
 !     
 !     > Loading repositories with available runtimes and extensions
 !     > Updating dependencies
 !     > Your requirements could not be resolved to an installable set of packages.
 !     > 
 !     >   Problem 1
 !     >     - composer.json/composer.lock requires php ~7.2.0 -> no matching package found.
 !     > 
 !     
 !     For reference, the following runtimes are currently available:
 !     
 !     PHP:  8.0.2, 8.0.1, 8.0.0, 8.0.0RC4, 7.4.15, 7.4.14, 7.4.13, 
 !     7.4.12, 7.3.27, 7.3.26, 7.3.25, 7.3.24
 !     
 !     Please verify that all requirements for runtime versions in
 !     'composer.lock' are compatible with the list above, and ensure
 !     all required extensions are available for the desired runtimes.
 !     
 !     When choosing a PHP runtimes and extensions, please also ensure
 !     they are available on your app's stack (heroku-20), and select
 !     a different stack if needed after consulting the article below.
 !     
 !     For a list of supported runtimes & extensions on Heroku, please
 !     refer to: https://devcenter.heroku.com/articles/php-support
 !     
 !     REMINDER: the following warnings were emitted during the build;
 !     check the details above, as they may be related to this error:
 !     - Requested version for package 'php' not available
 !     Push rejected, failed to compile PHP app.
 !     Push failed`

**Comment by Ren232** [comment]
I've pushed a fix for that and it should now work.
