### ISSUE TITLE
can't upload files

### ISSUE THREAD

**Issue by ClayTeck** [Ren232/mcgg#4]
so, I am trying to upload files, but they are not uploading.
I mean, files are showing on the upload page, uploading progress bar is 100%, it disappears, appears checkmark on file, but when I return on home directory there no new files. What am i doing wrong or why it doesn't work?
(not good in English, sorry)

**Comment by waaberi** [comment]
For me, it actually worked. Maybe try again.

EDIT: I learned that apparently it only works for small sized files.

**Comment by Ren232** [comment]
The file uploader inside the panel is only ment to be used as a uploader for plugins etc. If you want to include a custom version, you will need to fork the project and edit the code.
