### ISSUE TITLE
The server deletes itself sometimes Please help I spent 2 hours setting it up and the other day it said my login info isnt correct

### ISSUE THREAD

**Issue by voyantt** [Ren232/mcgg#7]

**Comment by minecrafttut** [comment]
Yeah i had the same issue. Sometimes it will work properly sometimes it won't. What I did was going back to panel/install.php again to reset.

**Comment by cyb3rpir4te** [comment]
The total ram of a free dyno is limited to 512mb.
When the ram usage is more than 512mb, it will reset.
