### ISSUE TITLE
Hello Im Have Problem In

### ISSUE THREAD

**Issue by SolDevelop** [Ren232/mcgg#9]
The Problem Is The Max Upload Size Is 256 MiB I Will Fix

**Comment by SolDevelop** [comment]
And When I Upload File Bigger Than 5 MB Is Not Finished It Take Long Time

**Comment by cyb3rpir4te** [comment]
Fix F0lder Permission

**Comment by NichuNaizam** [comment]
Heroku routers will make a upload or download process for 30 seconds if more time is taken the process is terminated
